server:
  port: 10010
#logging:
#  level:
#    cn.itcast: debug
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
spring:
  cloud:
    gateway:
      routes:
        - id: GoUserService #规则id
          uri: lb://user-service #负载均衡到user-service服务上
          predicates:
            - Path=/tb-user/** #端口号后边是不是以tb-user开头，是的换就负载均衡到user-service服务上
        - id: GoOrderService
          uri: lb://order-service
          predicates:
            - Path=/tb-order/** #端口号后边是不是以tb-user开头，是的换就负载均衡到user-service服务上
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.46.130:3306/cloud_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: general
      password: general

#mybatis依赖和数据库配置缺一不可，只要有缺的getway就没办法启动
